version: "3"
services:

  eureka-server:
    image: springcloud/eureka
    hostname: eureka-server
    ports:
      - 8761:8761

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mysql:
    image: mysql
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - C:/sonarqube

