version: "3"
services:

  desafio-labs:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"


