spring:
  application:
    name: desafio-luizalabs
  data:
    mongodb:
      host: localhost
      port: 27017
      database: desafio-luizalabs

server:
  port: 8080

swagger:
  version: 1.0
  description : Desafio Tecnico LuizaLabs